# Generated by Django 5.2.11 on 2026-03-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arcana', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major')], db_comment='type of Arcana', max_length=5)),
            ],
            options={
                'db_table': 'card',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='a name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, db_comment='desc description', null=True)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'deck',
                'db_table_comment': 'Taro deck',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='rank name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'rank',
                'db_table_comment': 'Minor Arcana ranks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='a name', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'source',
                'db_table_comment': 'Sources of interpretations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='spread name', max_length=100, unique=True)),
                ('major_arcana', models.BooleanField()),
                ('minor_arcana', models.BooleanField()),
                ('upside_down', models.BooleanField()),
                ('num_cards', models.SmallIntegerField(db_comment='number of cards in the spread')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spread',
                'db_table_comment': 'Card spreads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='name as nominative', max_length=100, unique=True)),
                ('genitive', models.CharField(db_comment='name as genitive', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suit',
                'db_table_comment': 'Minor Arcana suits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('card', models.OneToOneField(db_column='card', db_comment='card id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='image', serialize=False, to='api.card')),
                ('path', models.CharField(db_comment='relative path to the card image', max_length=255)),
            ],
            options={
                'db_table': 'card_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CardMajor',
            fields=[
                ('card', models.OneToOneField(db_column='card', db_comment='reference to card id, primary key', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='major', serialize=False, to='api.card')),
                ('number', models.SmallIntegerField(db_comment='ordinal number in a deck')),
                ('name', models.CharField(db_comment='card name', max_length=50)),
                ('orgname', models.CharField(blank=True, db_comment='original name', max_length=50, null=True)),
            ],
            options={
                'db_table': 'card_major',
                'db_table_comment': 'Major Arcana cards',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(db_column='deck', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='api.deck'),
        ),
        migrations.CreateModel(
            name='CardMinor',
            fields=[
                ('card', models.OneToOneField(db_column='card', db_comment='reference to card id, primary key', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='minor', serialize=False, to='api.card')),
                ('rank', models.ForeignKey(db_column='rank', db_comment='reference to rank', on_delete=django.db.models.deletion.DO_NOTHING, to='api.rank')),
                ('suit', models.ForeignKey(db_column='suit', db_comment='reference to suit', on_delete=django.db.models.deletion.DO_NOTHING, to='api.suit')),
            ],
            options={
                'db_table': 'card_minor',
                'db_table_comment': 'Minor Arcana cards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MeaningMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(db_comment='card number')),
                ('position', models.CharField(choices=[('straight', 'Straight'), ('reverted', 'Reverted')], db_comment='card position', max_length=8)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='major_meanings', to='api.source')),
            ],
            options={
                'db_table': 'meaning_major',
                'managed': True,
                'unique_together': {('number', 'position', 'source')},
            },
        ),
        migrations.CreateModel(
            name='DeckSource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('deck', models.ForeignKey(db_column='deck', on_delete=django.db.models.deletion.DO_NOTHING, related_name='deck_sources', to='api.deck')),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_decks', to='api.source')),
            ],
            options={
                'db_table': 'deck_source',
                'managed': True,
                'unique_together': {('deck', 'source')},
            },
        ),
        migrations.CreateModel(
            name='MeaningMinor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('straight', 'Straight'), ('reverted', 'Reverted')], max_length=8)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('rank', models.ForeignKey(db_column='rank', on_delete=django.db.models.deletion.DO_NOTHING, related_name='minor_meanings', to='api.rank')),
                ('source', models.ForeignKey(db_column='source', on_delete=django.db.models.deletion.DO_NOTHING, related_name='minor_meanings', to='api.source')),
                ('suit', models.ForeignKey(db_column='suit', on_delete=django.db.models.deletion.DO_NOTHING, related_name='minor_meanings', to='api.suit')),
            ],
            options={
                'db_table': 'meaning_minor',
                'managed': True,
                'unique_together': {('suit', 'rank', 'position', 'source')},
            },
        ),
    ]
