# Generated by Django 5.2.11 on 2026-03-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='sources',
            field=models.ManyToManyField(related_name='decks', through='api.DeckSource', to='api.source'),
        ),
    ]
